### ISSUE TITLE
Enemy HP Bars

### ISSUE THREAD

**Issue by monoai** [monoai/GDAPDEV_MP#12]
Very important for the player to distinguish they're actually dealing damage.

**Comment by havderick** [comment]
- [x] Player HP
- [x] Enemies HP

**Comment by havderick** [comment]
> * [x]  Player HP
> * [x]  Enemies HP

Both HP bars are implemented but...

- Player HP bar still needs DamagePlayer function from EnemyWeaponLogic to work properly.
- Enemies HP bar is also fully functioning but required the EnemyObjs to be parented under MainCanvas. This is already done but the FirePos is left at the original set position during EnemyBasicBehavior Start call. I believe it only needs another one-time function call for setting and it should be good.

**Comment by havderick** [comment]
HP Bar needs to reset everytime player is respawned
