### ISSUE TITLE
Joystick wouldn't appear on first touch.

### ISSUE THREAD

**Issue by monoai** [monoai/GDAPDEV_MP#21]
The joystick wouldn't appear when you first try to touch the screen and would have messed up values, thus making the player move slowly on the right as the movement relies from the joystick's position. 

There are currently 2 ways on my mind to fix this, where we look for the code inside the joystick itself and see what's making the joystick spawn inaccurately in the first place (possibly wrong coordinate system were used?) or to just remake the joystick into something simpler and controllable.

**Comment by havderick** [comment]
Refactored to use sir JR's joystick, although it seems like he essentially just tried to recreate the joystick asset pack with less inspector modifying capabilities. Main diff was the localPoint computation was weird for the asset pack in this case.
