### ISSUE TITLE
Settings and preferences

### ISSUE THREAD

**Issue by monoai** [monoai/GDAPDEV_MP#7]
Our settings should actually store the player's preferences for either that session or any future session onwards, plus the settings they choose should apply to the game itself.
Probably one way to do this is to either use PlayerPrefs or our DataManager, but let's aim for elegance yeah?

## Remaining Tasks
- [x] #13 (More Values)
- [x] #8 (Movement Speed)
- [x] Control types
- [x] Programming the game to actually recognize the settings

**Comment by havderick** [comment]
Aside from the audio sliders and the option to select player control preference, what else do we want for the settings menu? (like mute toggle, notifs toggle, etc.)

**Comment by monoai** [comment]
As of now, the additional settings I'm thinking of are Control Settings where a player can switch out two types of control they can choose (Joystick or Drag the screen) and possibly a Movement Speed option to make the ship faster or slower. The latter's probably something optional right now but the former is important since that's both of our inputs being utilized.

**Comment by havderick** [comment]
Joystick is available for use and is restricted to the left side for landscape orientation as of now. It currently does nothing.

**Comment by monoai** [comment]
Though the last task can probably an entirely new issue by itself, unless it gets larger, I think it's best to just add it here while also emphasizing its urgency.
